site_name: Team 2928 FRC Training
site_url: https://2928-frc-programmer-training.readthedocs.io
nav:
    - Home: index.md
    - 'Romi Robot':
        - 'Subsystems and Commands': 
            - 'Romi/SC/romiSCIndex.md'
            - 'Romi Development Environment': Romi/SC/romiDev.md
            - 'Romi Example Code': Romi/SC/romiExample.md
            - 'Basic Robot Structure': Romi/SC/romiStructure.md
            - 'Subsystems': Romi/SC/romiSubsystems.md
            - 'Commands': Romi/SC/romiCommands.md
            - 'Command Groups': Romi/SC/romiCommandGroups.md
            - 'Shuffleboard': Romi/SC/romiShuffleboard.md
        - 'Robot Control':
            - 'Romi/Control/romiControlIndex.md'
            - Robot Characterization: Romi/Control/romiCharacterization.md
            - Motion PID Control: Romi/Control/romiPID.md
            - Trajectory Following: Romi/Control/romiTrajectory.md
            - State Space Control: Romi/Control/romiStateSpace.md
            - Controlling Servos: Romi/Control/romiServos.md
        - 'Vision Processing':
            - 'Romi/Vision/romiVisionIndex.md'
            - Basic Vision Program: Romi/Vision/romiBasicVision.md
            - Image Processing: Romi/Vision/romiImageProcessing.md
            - Line Following: Romi/Vision/romiLineFollow.md
        - 'Romi Robot Software':
            - 'Romi/RomiSoftware/romiSoftwareIndex.md'
            - RaspberryPi Software: Romi/RomiSoftware/romiPiSoftware.md
            - Micro Controller Firmware: Romi/RomiSoftware/romiFirmware.md

    - 'Development Tools': 
        - Visual Studio Code: Tools/vscode.md
        - Git and Github: Tools/git.md
        - Robot Simulator: Tools/simulator.md
        - Shuffleboard: Tools/shuffleboard.md

    - 'Programming': 
        - Introduction to Programming: Programming/introProgramming.md
        - Data Structures: Programming/dataStructures.md
        - Procedures: Programming/procedures.md
        - Objects: Programming/objects.md
        - State Machines: Programming/stateMachines.md

    - 'Robotics Concepts': 
        - 'Robot Systems': 
            - Introduction: Concepts/RobotSystem/robotSystemsIndex.md   
            - Robot Systems: Concepts/RobotSystem/intro.md
            - Sensors: Concepts/RobotSystem/sensors.md
            - Actuators: Concepts/RobotSystem/actuators.md
            - Control Algorithms: Concepts/RobotSystem/control.md
        - 'Dynamics': 
            - Concepts/Dynamics/dynamicsIndex.md
            - Mobile Robot Kinematics: Concepts/Dynamics/kinematics.md
            - Position & Orientation: Concepts/Dynamics/geometry.md
            - Dynamical Systems: Concepts/Dynamics/dynamicalSystems.md
            - Paths & Trajectories: Concepts/Dynamics/pathsTrajectories.md
        - Optimal Estimation:
            - Concepts/OptimalEstimation/optimalEstimationIndex.md
            - Pose Estimation: Concepts/OptimalEstimation/poseEstimation.md
            - Random Processes: Concepts/OptimalEstimation/randomProcesses.md
            - Kalman Filters: Concepts/OptimalEstimation/kalmanFilters.md
        - Control:
            - Concepts/Control/controlIndex.md
            - Concepts/Control/classicalControl.md
            - Concepts/Control/stateSpaceControl.md
            - Concepts/Control/LQR.md
    - 'Vision': 
        - Introduction: Vision/introVision.md

theme: readthedocs