site_name: Team 2928 FRC Training
site_url: https://2928-frc-programmer-training.readthedocs.io
nav:
    - Home: 
        - index.md
        - 'Setup Development Environment':
            - SoftwareInstall/softwareIndex.md
            - SoftwareInstall/vscodeSoftware.md
            - SoftwareInstall/vendorSoftware.md
            - SoftwareInstall/visionSoftware.md
            - Tools/git.md
        - 'Setup Testing Environment': 
            - SoftwareInstall/testingIndex.md
            - Romi/SC/romiDev.md
            - SoftwareInstall/romiPiSoftware.md
            - SoftwareInstall/romiFirmware.md
            - SoftwareInstall/rioSoftware.md   
# - Romi Robot:
        - 'Romi Robot Basics': 
            - Romi/SC/romiSCIndex.md
            - Romi/SC/romiExample.md
            - Romi/SC/romiStructure.md
            - Romi/SC/romiSubsystems.md
            - Romi/SC/romiCommands.md
            - Romi/SC/romiTelemetry.md
            - Romi/SC/romiGPIO.md
        - 'Romi Robot Control':
            - Romi/Control/romiControlIndex.md
            - Romi/Control/romiCharacterization.md
            - Romi/Control/romiPID.md
            - Romi/Control/romiTrajectory.md
            - Romi/Control/romiStateSpace.md
            - Romi/Control/romiServos.md
            - Romi/Control/romiArm.md
        - 'Romi Vision Processing':
            - Romi/Vision/romiVisionIndex.md
            - Romi/Vision/romiBasicVision.md
            - Romi/Vision/romiImageProcessing.md
            - Romi/Vision/romiLineFollow.md
        

        - 'Programming': 
            - Programming/introProgramming.md
            - Programming/dataStructures.md
            - Programming/procedures.md
            - Programming/objects.md
            - Programming/stateMachines.md  
            - Tools/vscode.md     

        # - 'Robotics Concepts': 
        - 'Robot Systems': 
            - Concepts/RobotSystem/robotSystemsIndex.md   
            - Concepts/RobotSystem/intro.md
            - Concepts/RobotSystem/sensors.md
            - Concepts/RobotSystem/actuators.md
            - Concepts/RobotSystem/drivetrains.md
            - Concepts/RobotSystem/control.md
            - Concepts/RobotSystem/communications.md
        - 'Dynamics': 
            - Concepts/Dynamics/dynamicsIndex.md
            - Concepts/Dynamics/kinematics.md
            - Concepts/Dynamics/geometry.md
            - Concepts/Dynamics/dynamicalSystems.md
            - Concepts/Dynamics/pathsTrajectories.md
        - 'Optimal Estimation':
            - Concepts/OptimalEstimation/optimalEstimationIndex.md
            - Concepts/OptimalEstimation/poseEstimation.md
            - Concepts/OptimalEstimation/randomProcesses.md
            - Concepts/OptimalEstimation/kalmanFilters.md
        - 'Control':
            - Concepts/Control/controlIndex.md
            - Concepts/Control/classicalControl.md
            - Concepts/Control/stateSpaceControl.md
            - Concepts/Control/LQR.md
        - 'Vision': 
            - Vision/introVision.md
        - 'Machine Learning':
            - MachineLearning/MLIndex.md
            - MachineLearning/MLProcessImages.md
            - 'Training the Model':
                - MachineLearning/MLTrainingIndex.md
                - MachineLearning/MLColabTraining.md
                - MachineLearning/MLAxonTraining.md
            - 'Deployment':
                - MachineLearning/MLDeploymentIndex.md
                - MachineLearning/MLDeploymentScript.md
                - MachineLearning/MLRomiDeploymentOAK.md
                # - MachineLearning/MLJetsonDeploymentOAK.md
                # - MachineLearning/MLRomiDeployment.md
                # - MachineLearning/MLJetsonDeployment.md
            - MachineLearning/MLControl.md    

theme: readthedocs
# python:
#   install:
#     - requirements: requirements.txt